### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chuchana**
Added info for compiling on Mac OS X

### CODE REVIEW

**Comment by micdah** [comment]
It should not be necessary to checkout that branch, `master` should compile on macOS.

I have compiled on macOS recently - are you experiencing issues getting it to compile?

**Comment by chuchana** [comment]
I got this error when I tried to compile the master branch:
````
RtMidi.cpp:3346:5: error: use of undeclared identifier 'sem_timedwait'
    sem_timedwait(&data->sem_cleanup, &ts);
    ^
````
I tried both `autogen` -> `make` and `autogen` -> `configure` -> `make`.
Same thing with https://github.com/thestk/rtmidi.

Then I saw the other branch which solved this, so I thought it was "the right way" and that it made sense to include it in the readme file so others didn't need to look for it.

If you need any more information I'll gladly provide it.

**Comment by micdah** [comment]
Just compiled from `master` to make sure - still works for me.

Could you take a look here, and see if you have the required dependencies (autoconf, automake and libtool) and try compiling using the three commands I list there?
https://github.com/micdah/RtMidi.Core/blob/master/RTMIDI.md

**Comment by chuchana** [comment]
Strange. It did not work for me with the steps you linked to. The dependencies were already installed (from homebrew) and up to date.

But if I'm the only one for whom the master doesn't compile and the `fix-macos-dylib` branch works, I'm fine with that.

**Pull request closed without merging**
